/**
 * The Worker entry: OpenNext's generated worker, plus the nightly backup.
 *
 * `fetch` is OpenNext's, unchanged. `scheduled` is the Cron Trigger in
 * wrangler.jsonc. It runs the backup by calling /api/cron/backup through the
 * same `fetch`, bearing CRON_SECRET, so the route's auth check, its database
 * access and its KV write are the exact code an HTTP call would run. Nothing
 * leaves the Worker: the request is handed to the handler in-process.
 */

// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it is
// missing in a fresh checkout (and in CI) and present after a build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from './.open-next/worker.js'

type Handler = {
  fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext): Promise<Response>
}
const openNext = handler as Handler

export default {
  fetch: openNext.fetch,

  async scheduled(controller, env, ctx) {
    const secret = (env as CloudflareEnv & { CRON_SECRET?: string }).CRON_SECRET
    const res = await openNext.fetch(
      new Request('https://house-ladder.internal/api/cron/backup', {
        headers: { authorization: `Bearer ${secret ?? ''}` },
      }),
      env,
      ctx,
    )
    const body = await res.text()
    // A failed backup must fail the cron invocation, so it shows as an error
    // in the dashboard's Cron Events and Workers Logs rather than passing.
    if (!res.ok) throw new Error(`Backup failed (${controller.cron}): ${res.status} ${body}`)
    console.log(`Backup ok (${controller.cron}): ${body}`)
  },
} satisfies ExportedHandler<CloudflareEnv>
